# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'U17_ZSY' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SnapKitExtend'
pod 'Then'
pod 'Moya'
pod 'HandyJSON'
pod 'Kingfisher'
pod 'Reusable'
pod 'LLCycleScrollView'
pod 'MJRefresh'
pod 'MBProgressHUD'
pod 'HMSegmentedControl'
pod 'IQKeyboardManagerSwift'
pod 'EmptyDataSet-Swift'
pod 'UINavigation-SXFixSpace'



end
